### ISSUE TITLE
balena dbus config file / hostapps

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/helium-miner-software#105]
In order to better support multiple hardwares, we ideally need balena hostapps to be available to us.

Otherwise, for every hardware variant we will need a custom machine type on balena to pull in the dbus config file

```
<!DOCTYPE busconfig PUBLIC
 "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>
  <policy user="root">
    <allow own="com.helium.Miner"/>
    <allow send_interface="com.helium.Miner"/>
  </policy>
  <policy context="default">
     <allow send_destination="com.helium.Miner"/>
  </policy>
</busconfig>
```

Ref: https://github.com/helium/miner/blob/master/config/com.helium.Miner.conf

This needs to be placed on the host os at `/etc/dbus-1/system.d` as has been done here for the nebra-hnt device type on balena https://github.com/balena-os/balena-raspberrypi/blob/master/layers/meta-balena-raspberrypi/recipes-core/dbus/dbus_%25.bbappend

Currently, we have to manually add this for different devices types by removing read only from filesystem and adding the file in https://forums.balena.io/t/i-want-to-edit-host-os-read-only-files/21266

**Comment by vpetersson** [comment]
Just FYI @marvinmarnold

**Comment by shawaj** [comment]
Once these commits are merged:

- h
- h
- h

We can then update docker-compose.yml to the following (changing out for updated container tags):
```
version: '2'

services:

  gateway-config:
    image: nebraltd/hm-config:0e0a9f00c307a80be6782c4376be70f16fa39c36
    depends_on:
      - dbus-session
    environment:
      - FIRMWARE_VERSION=2021.09.16.1
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
      - DBUS_SESSION_BUS_ADDRESS=tcp:host=localhost,port=55884
    privileged: true
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    volumes:
      - miner-storage:/var/data
    labels:
      io.balena.features.sysfs: '1'
      io.balena.features.kernel-modules: '1'
      io.balena.features.dbus: '1'
    stop_signal: SIGINT

  packet-forwarder:
    image: nebraltd/hm-pktfwd:477eeda57ca9ebcb3909eebb8e869776a95b1668
    privileged: true
    volumes:
      - pktfwdr:/var/pktfwd

  helium-miner:
    image: nebraltd/hm-miner:6077a01d35a6cf3ed6ee740f6e927b66eccb4d42
    depends_on:
      - dbus-session
    expose:
      - "1680"
      - "4467"
    ports:
      - "44158:44158/tcp"
    volumes:
      - miner-storage:/var/data
      - miner-log:/var/log/miner
      - pktfwdr:/var/pktfwd
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS=tcp:host=dbus-session,port=55884
      - RELEASE_BUMPER=foobar

  diagnostics:
    image: nebraltd/hm-diag:b49f821d5202c24a9428f6f7831cb6380db3df48
    depends_on:
      - dbus-session
    environment:
      - FIRMWARE_VERSION=2021.09.16.1
      - DBUS_SESSION_BUS_ADDRESS=tcp:host=dbus-session,port=55884
    volumes:
      - pktfwdr:/var/pktfwd
      - miner-storage:/var/data
    ports:
      - "80:5000"
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    labels:
      io.balena.features.sysfs: '1'

  gwmfr:
    image: nebraltd/hm-gwmfr:f84834b70e34520e63d4a2dda521a198feb66b71
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    restart: on-failure

  upnp:
    image: nebraltd/hm-upnp:4e419f5bb5d59b31fcd1f81e0c94f7e94cd9ebee
    network_mode: "host"
    restart: on-failure
    volumes:
      - pktfwdr:/var/pktfwd

  dbus-session:
    image: balenablocks/dbus:rpi-0.0.2
    restart: always
    expose:
      - "55884"

volumes:
  miner-storage:
  miner-log:
  pktfwdr:

```
