### ISSUE TITLE
add balena.yml

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/helium-miner-software#165]
for open fleets we need to add a balena.yml - example below:
https://hub.balena.io/nebraltd/helium-miner

```
name: "Nebra Helium Miner"
type: sw.application
description: >-
  Software stack for Helium Miners
joinable: true
post-provisioning: >-
  For support you can [open an issue](https://github.com/NebraLtd/helium-miner-software/issues) on the repo or
  reach out to us via one of the methods listed [on our support page](https://helium.nebra.com/support).
assets:
  repository:
    type: blob.asset
    data:
      url: "https://github.com/NebraLtd/helium-miner-software"
  logo:
    type: blob.asset
    data:
      url: >-
        https://cdn.shopify.com/s/files/1/0071/2281/3001/files/Nebra-Icon-Blue_bb758eaa-b10d-4ea6-a55e-babd69135b69.png?v=1620938774
data:
  defaultDeviceType: raspberrypi3-64
  applicationConfigVariables:
    - RESIN_HOST_CONFIG_core_freq: 400
  applicationEnvrionmentVariables:
    - VARIANT: 'DIY-PISLGH'
    - REGION_OVERRIDE: 'EU868'
    - FREQ: '868'
  supportedDeviceTypes:
    - raspberrypi3-64
    - raspberrypi4-64
    - nebra-hnt
version: 0.0.1
```
